### ISSUE TITLE
Binding constraints::Implicit::comparisonType

### ISSUE THREAD

**Issue by florent-lamiraux** [humanoid-path-planner/hpp-corbaserver#121]
I am unable to bind method hpp::constraints::Implicit::comparisonType. If I add the following lines to
interface Implicit in constraints.idl
```
    intSeq getComparisonType() raises (Error);
    //-> comparisonType
```
I get the compilation error below. Of course I expect to get a compilation error from gcc, but I do not understand why omniidl fails to parse those line. If I replace `intSeq` by `floatSeq`, omniidl successfully generates python and C++ files and I get later a compilation error which is the expected behavior. I tried several workaround like replacing `intSeq` by `sequence<long>` but without any success.
```
Traceback (most recent call last):
  File "/opt/openrobots/bin/omniidl", line 140, in <module>
    omniidl.main.main()
  File "/opt/openrobots/lib/omniidl/omniidl/main.py", line 451, in main
    bemodules[i].run(tree, backends_args[i])
  File "/home/florent/devel/hpp/src/hpp-corbaserver/cmake-modules/omniidl/cxx_impl/__init__.py", line 235, in run
    main.run(tree)
  File "/home/florent/devel/hpp/src/hpp-corbaserver/cmake-modules/omniidl/cxx_impl/main.py", line 116, in run
    tree.accept(bii)
  File "/opt/openrobots/lib/omniidl/omniidl/idlast.py", line 104, in accept
    def accept(self, visitor): visitor.visitAST(self)
  File "/home/florent/devel/hpp/src/hpp-corbaserver/cmake-modules/omniidl/cxx_impl/main.py", line 334, in visitAST
    n.accept(self)
  File "/opt/openrobots/lib/omniidl/omniidl/idlast.py", line 246, in accept
    def accept(self, visitor): visitor.visitModule(self)
  File "/home/florent/devel/hpp/src/hpp-corbaserver/cmake-modules/omniidl/cxx_impl/main.py", line 312, in visitModule
    n.accept(self)
  File "/opt/openrobots/lib/omniidl/omniidl/idlast.py", line 246, in accept
    def accept(self, visitor): visitor.visitModule(self)
  File "/home/florent/devel/hpp/src/hpp-corbaserver/cmake-modules/omniidl/cxx_impl/main.py", line 312, in visitModule
    n.accept(self)
  File "/opt/openrobots/lib/omniidl/omniidl/idlast.py", line 296, in accept
    def accept(self, visitor): visitor.visitInterface(self)
  File "/home/florent/devel/hpp/src/hpp-corbaserver/cmake-modules/omniidl/cxx_impl/main.py", line 511, in visitInterface
    store_return, do_return = self.retConversion (types.Type(c.returnType()))
  File "/home/florent/devel/hpp/src/hpp-corbaserver/cmake-modules/omniidl/cxx_impl/main.py", line 291, in retConversion
    print ("Unhandled sequence of", innerType.type().name())
AttributeError: Base instance has no attribute 'name'
src/CMakeFiles/generate_idl_cpp.dir/build.make:311: recipe for target 'src/hpp/constraints_idl/constraints-fwd.hh' failed
```

**Comment by jmirabel** [comment]
This issue seems inactive. @florent-lamiraux please, re-open if relevant.
