### ISSUE TITLE
Running tests in docker

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/hpp-corbaserver#57]
omniName service must be running to launch the tests, and it doesn't seem to work on docker for now:

```
$ rm -v /var/log/omniorb*
removed '/var/log/omniorb-nameserver.log'
$ service omniorb4-nameserver restart
 * Restarting omniORB name server:  omniNames
   ...done.
$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  5.0  0.0  18224  3020 ?        Ss   13:37   0:00 /bin/bash
root         9  0.0  0.0  18320  2784 ?        S    13:37   0:00 /bin/bash
root        21  0.0  0.0   4376    88 ?        R    13:37   0:00 start-stop-daemon --start --quiet --background --pidfile /var/run/omniNames.pid --make-pidfile --exec /usr/bin/omniNames -- -errlog /var/log/omniorb-nameserver.log
root        22  0.0  0.0  34424  2896 ?        R    13:37   0:00 ps aux
$ ctest -VV
UpdateCTestConfiguration  from :/root/robotpkg/path/hpp-corbaserver/work.runner-e7e27102-project-224-concurrent-3/hpp-corbaserver-4.2.0/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/root/robotpkg/path/hpp-corbaserver/work.runner-e7e27102-project-224-concurrent-3/hpp-corbaserver-4.2.0/build/DartConfiguration.tcl
Test project /root/robotpkg/path/hpp-corbaserver/work.runner-e7e27102-project-224-concurrent-3/hpp-corbaserver-4.2.0/build
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: robot.py

1: Test command: /usr/bin/python2.7 "/root/robotpkg/path/hpp-corbaserver/work.runner-e7e27102-project-224-concurrent-3/hpp-corbaserver-4.2.0/tests/robot.py"
1: Environment variables: 
1:  PYTHONPATH=/root/robotpkg/path/hpp-corbaserver/work.runner-e7e27102-project-224-concurrent-3/hpp-corbaserver-4.2.0/build/src:/usr/lib/omniidl/omniidl_be
1: Test timeout computed to be: 9.99988e+06
1: E
1: ======================================================================
1: ERROR: test_createRobotFromPython (__main__.Test)
1: ----------------------------------------------------------------------
1: Traceback (most recent call last):
1:   File "/root/robotpkg/path/hpp-corbaserver/work.runner-e7e27102-project-224-concurrent-3/hpp-corbaserver-4.2.0/tests/robot.py", line 18, in setUp
1:     self.client = Client()
1:   File "/root/robotpkg/path/hpp-corbaserver/work.runner-e7e27102-project-224-concurrent-3/hpp-corbaserver-4.2.0/build/src/hpp/corbaserver/client.py", line 66, in __init__
1:     self.rootContext = obj._narrow(CosNaming.NamingContext)
1:   File "/usr/lib/python2.7/dist-packages/omniORB/CORBA.py", line 798, in _narrow
1:     return _omnipy.narrow(self, repoId, 1)
1: TRANSIENT: CORBA.TRANSIENT(omniORB.TRANSIENT_ConnectFailed, CORBA.COMPLETED_NO)
1: 
1: ----------------------------------------------------------------------
1: Ran 1 test in 0.017s
1: 
1: FAILED (errors=1)
1/1 Test #1: robot.py .........................***Failed    0.13 sec
```

**Comment by jmirabel** [comment]
You can safely ignore this test. The problem might be that `hppcorbaserver` is not running.

**Comment by nim65s** [comment]
This is still on my todolist, related to #67
