### ISSUE TITLE
AttributeError: attribute '__doc__' of 'type' objects is not writable on 18.04

### ISSUE THREAD

**Issue by nim65s** [humanoid-path-planner/hpp-corbaserver#76]
Hi,

The test `py-robot` does not pass on 18.04 after #75, with the following error:
```
2/2 Test #1: py-robot .........................***Failed    0.24 sec
Traceback (most recent call last):
  File "…/tests/robot.py", line 6, in <module>
    from hpp.corbaserver import Client
  File "…/src/hpp/corbaserver/__init__.py", line 1, in <module>
    from .client import Client
  File "…/src/hpp/corbaserver/client.py", line 8, in <module>
    import hpp_idl.hpp.corbaserver
  File "…/src/hpp_idl/hpp/__init__.py", line 11, in <module>
    import hpp_stubs.corbaserver.robot_idl
  File "…/src/hpp_stubs/corbaserver/robot_idl.py", line 495, in <module>
    _0_hpp.corbaserver._objref_Robot.__doc__ = _0_hpp.corbaserver.Robot__doc__
AttributeError: attribute '__doc__' of 'type' objects is not writable
```

**Comment by jmirabel** [comment]
Interesting...
What version of python is used ?

**Comment by nim65s** [comment]
python 2

**Comment by jmirabel** [comment]
It was decided to drop IDL documentation of Python 2 bindings (and maintain it for Python 3).
